import { readText } from '../../utils/file';
import { coreFiles, dispatcherFlow, flowNames, skillFiles } from '../../config/constants';

export function collectCoreSummary() {
  return coreFiles.map((file) => `- .ai/core/${file}`).join('\n');
}

export function collectFlowSummary() {
  return [
    `- /ai: .ai/flows/${dispatcherFlow}.md`,
    ...flowNames.map((flow) => `- /ai:${flow}: .ai/flows/${flow}.md`),
  ].join('\n');
}

export function collectSkillSummary() {
  return skillFiles.map((file) => `- superpowers/skills/${file}`).join('\n');
}

export function buildRulesDocument(tool: string) {
  return `# MsgFi AI Rules for ${tool}\n\n<!-- Generated by pnpm ai sync. Edit .ai/core, .ai/flows, and superpowers/skills instead. -->\n\n## Required Workflow\n\n1. Read .ai/core/workflow.md before starting AI-assisted work.\n2. For normal guided work, accept /ai <change> and dispatch to the next suitable flow.\n3. Read the active change under openspec/changes/<change>.\n4. Use the relevant /ai flow.\n5. Search Knowledge Memory with pnpm ai knowledge:search before propose/plan/apply when relevant.\n6. Keep edits scoped to the active change.\n7. Run pnpm ai check before finishing.\n\n## Integration Modes\n\n- lightweight: use MsgFi built-in compatible rules.\n- official: prefer repo-local official integration only when installed; never use global installs implicitly.\n- hybrid: combine MsgFi rules with repo-local official integration when installed.\n\n## Knowledge Memory\n\n- Use pnpm ai knowledge:search <keywords> --limit 10.\n- Read only returned summaries, not the full harness/memory/knowledge JSONL files.\n- During finish, run pnpm ai knowledge:suggest <change> --write when tool access is available.\n- Add only confirmed reusable knowledge during finish with pnpm ai knowledge:add.\n- Final reports must say what Knowledge Memory was searched, suggested, added, or why it was skipped.\n\n## Core Rules\n\n${collectCoreSummary()}\n\n## Conversation Flows\n\n${collectFlowSummary()}\n\n## Skills\n\n${collectSkillSummary()}\n`;
}

export function buildDispatcherDocument() {
  const flowText = readText(`.ai/flows/${dispatcherFlow}.md`);
  return `# /ai\n\n<!-- Generated by pnpm ai sync. Edit .ai/flows/${dispatcherFlow}.md instead. -->\n\n${flowText}\n\n## Shared Context\n\nBefore acting, read:\n\n- .ai/core/workflow.md\n- harness/state.json when present\n- openspec/changes/<change>/proposal.md when present\n- openspec/changes/<change>/tasks.md when present\n- openspec/changes/<change>/acceptance.md when present\n\nUse the specific /ai:* flow selected by the dispatcher.\n`;
}

export function buildCommandDocument(flow: string) {
  const flowText = readText(`.ai/flows/${flow}.md`);
  return `# /ai:${flow}\n\n<!-- Generated by pnpm ai sync. Edit .ai/flows/${flow}.md instead. -->\n\n${flowText}\n\n## Shared Context\n\nBefore acting, read:\n\n- .ai/core/workflow.md\n- openspec/changes/<change>/proposal.md\n- openspec/changes/<change>/tasks.md\n- openspec/changes/<change>/acceptance.md\n\nFinish with \`pnpm ai check\` when the flow changes code.\n`;
}
