import { Command } from 'commander';
import { flowNames, dispatcherFlow } from '../config/constants';
import { readText, writeGeneratedFile } from '../utils/file';

export function registerFlowCommands(program: Command) {
  const flow = program.command('flow').description('Workflow management');

  flow.command('list').description('List available flows').action(flowListCommand);

  flow.command('show <flow>').description('Show flow definition').action(flowShowCommand);

  flow.command('sync').description('Sync flow documents').action(flowSyncCommand);
}

function flowListCommand() {
  console.log(
    JSON.stringify(
      {
        dispatcher: dispatcherFlow,
        flows: flowNames,
      },
      null,
      2,
    ),
  );
}

function flowShowCommand(flowName: string) {
  const flowPath = `.ai/flows/${flowName}.md`;
  try {
    const content = readText(flowPath);
    console.log(content);
  } catch {
    console.error(`Flow not found: ${flowName}`);
    process.exitCode = 1;
  }
}

function flowSyncCommand() {
  for (const tool of ['codex', 'trae', 'qoder', 'cursor']) {
    const rulesPath = tool === 'codex' ? '.codex/rules.md' : `.${tool}/rules.md`;
    const rulesContent = buildRulesDocument(tool);
    writeGeneratedFile(rulesPath, rulesContent);

    const dispatcherPath = tool === 'codex' ? '.codex/commands/ai.md' : `.${tool}/commands/ai.md`;
    const dispatcherContent = buildDispatcherDocument();
    writeGeneratedFile(dispatcherPath, dispatcherContent);

    for (const flow of flowNames) {
      const flowPath =
        tool === 'codex' ? `.codex/commands/ai:${flow}.md` : `.${tool}/commands/ai:${flow}.md`;
      const flowContent = buildCommandDocument(flow);
      writeGeneratedFile(flowPath, flowContent);
    }
  }
  console.log(`Flows synced for tools: codex, trae, qoder, cursor`);
}

function buildRulesDocument(tool: string) {
  return `# MsgFi AI Rules for ${tool}\n\n<!-- Generated by pnpm ai sync. Edit .ai/core, .ai/flows, and superpowers/skills instead. -->\n\n## Required Workflow\n\n1. Read .ai/core/workflow.md before starting AI-assisted work.\n2. For normal guided work, accept /ai <change> and dispatch to the next suitable flow.\n3. Read the active change under openspec/changes/<change>.\n4. Use the relevant /ai flow.\n5. Search Knowledge Memory with pnpm ai knowledge:search before propose/plan/apply when relevant.\n6. Keep edits scoped to the active change.\n7. Run pnpm ai check before finishing.\n\n## Integration Modes\n\n- lightweight: use MsgFi built-in compatible rules.\n- official: prefer repo-local official integration only when installed; never use global installs implicitly.\n- hybrid: combine MsgFi rules with repo-local official integration when installed.\n\n## Knowledge Memory\n\n- Use pnpm ai knowledge:search <keywords> --limit 10.\n- Read only returned summaries, not the full harness/memory/knowledge JSONL files.\n- During finish, run pnpm ai knowledge:suggest <change> --write when tool access is available.\n- Add only confirmed reusable knowledge during finish with pnpm ai knowledge:add.\n- Final reports must say what Knowledge Memory was searched, suggested, added, or why it was skipped.\n\n## Core Rules\n\n${collectCoreSummary()}\n\n## Conversation Flows\n\n${collectFlowSummary()}\n\n## Skills\n\n${collectSkillSummary()}\n`;
}

function buildDispatcherDocument() {
  const flowText = readText(`.ai/flows/${dispatcherFlow}.md`);
  return `# /ai\n\n<!-- Generated by pnpm ai sync. Edit .ai/flows/${dispatcherFlow}.md instead. -->\n\n${flowText}\n\n## Shared Context\n\nBefore acting, read:\n\n- .ai/core/workflow.md\n- harness/state.json when present\n- openspec/changes/<change>/proposal.md when present\n- openspec/changes/<change>/tasks.md when present\n- openspec/changes/<change>/acceptance.md when present\n\nUse the specific /ai:* flow selected by the dispatcher.\n`;
}

function buildCommandDocument(flow: string) {
  const flowText = readText(`.ai/flows/${flow}.md`);
  return `# /ai:${flow}\n\n<!-- Generated by pnpm ai sync. Edit .ai/flows/${flow}.md instead. -->\n\n${flowText}\n\n## Shared Context\n\nBefore acting, read:\n\n- .ai/core/workflow.md\n- openspec/changes/<change>/proposal.md\n- openspec/changes/<change>/tasks.md\n- openspec/changes/<change>/acceptance.md\n\nFinish with \`pnpm ai check\` when the flow changes code.\n`;
}

function collectCoreSummary() {
  const coreFiles = [
    'project.md',
    'frontend.md',
    'api.md',
    'ui.md',
    'testing.md',
    'review.md',
    'workflow.md',
  ];
  return coreFiles.map((file) => `- .ai/core/${file}`).join('\n');
}

function collectFlowSummary() {
  return [
    `- /ai: .ai/flows/${dispatcherFlow}.md`,
    ...flowNames.map((flow) => `- /ai:${flow}: .ai/flows/${flow}.md`),
  ].join('\n');
}

function collectSkillSummary() {
  const skillFiles = ['planning.md', 'tdd.md', 'debugging.md', 'code-review.md', 'finishing.md'];
  return skillFiles.map((file) => `- superpowers/skills/${file}`).join('\n');
}
